### ISSUE TITLE
0xa1 - Confirmer l'inclusion ou pas des informations sur DevSecOps

### ISSUE THREAD

**Issue by romualdszkudlarek** [SPoint42/Top10#2]
Dans le paragraphe Suis-je vulnérable, en version en 2017, il y a des informations sur DevSecOps qui ne faisaient pas partie de la traduction en français 2013. Faut-il les rajouter à la traduction en français pour la version 2017?

**Comment by SPoint42** [comment]
Bien sûr !

La v2013 est juste là pour référence et gagner du temps parfois
