### ISSUE TITLE
Library = bibliothèque ou librairie ?

### ISSUE THREAD

**Issue by Awagi** [SPoint42/Top10#31]
Bonjour, je suis en train de relire et corriger des typos et fautes de français dans les traductions mais je m'interroge aussi sur d'autres points.

La traduction de `libraries` en français, s'accorde-t-on à dire `bibliothèques`, ce qui me paraît plus correct même dans un jargon de développeur, ou bien `librairies` ?

**Comment by jcpraud** [comment]
Bonjour,
Avis d'ancien développeur : 
- library = bibliothèque
- book shop = librairie

Ceci dit, c'est comme crypter/chiffrer, ça fait hurler les puristes mais entre dans les usages.

**Comment by SPoint** [comment]
+1


—

Ce mail est 100% RGPD compliant
Sébastien Gioria  +336 70 59 11 44<https://outlook.office.com/owa/?path=/mail/sentitems> – AppSecFR® - Vos Spécialistes en Sécurité Applicative
https://www.linkedin.com/in/gioria –  https://twitter.com/Spoint
Expert près la Cour d’Appel de Poitiers
OWASP French Leader




________________________________
De : jcpraud <notifications@github.com>
Envoyé : mercredi 3 octobre 2018 19:05
À : SPoint42/Top10
Cc : Subscribed
Objet : Re: [SPoint42/Top10] Library = bibliothèque ou librairie ? (#31)


Bonjour,
Avis d'ancien développeur :

  *   library = bibliothèque
  *   book shop = librairie

Ceci dit, c'est comme crypter/chiffrer, ça fait hurler les puristes mais entre dans les usages.
