### ISSUE TITLE
0x05 Introduction

### ISSUE THREAD

**Issue by inaz0** [SPoint42/Top10#32]
Dans le paragraphe Remerciements : 

> Un grand merci aux individus (plus de 500 !) qui ont pris le temps de répondre à l'étude industrielle. Votre voix a aidé à retenir deux nouveaux ajouts au Top 10. **Les commentaires, messagez** d'encouragements et critiques ont tous été appréciés. Nous savons que votre temps est précieux et tenons à vous dire merci.

=>  **Les commentaires, messages**

**Comment by SPoint42** [comment]
done
