### ISSUE TITLE
Relecture A5

### ISSUE THREAD

**Issue by jcpraud** [SPoint42/Top10#4]
Bonjour,

Je viens d'uploader ma traduction pour la section A5 : Contrôle d'accès.

**Comment by SPoint** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SPoint42/Top10] Relecture A5 (#4)](https://trello.com/c/VFmn7rR4/1-spoint42-top10-relecture-a5-4)

**Comment by SPoint42** [comment]
QQn a regardé ?

**Comment by SPoint42** [comment]
tjrs personne  ?

**Comment by Shosta** [comment]
Je ne sais pas si je peux aider sur ce point ou bien il y a des reviewers particuliers au projet?
Et je ne vois pas de Pull Request sur la section A5? Peut-être est-ce bon? Il faudrait fermer cette Issue dans ce cas là.

**Comment by SPoint42** [comment]
Ya pas de Pull car il y a pas eu de review ;) 
Donc pour l'instant il est pusher en traduction initiale
