### ISSUE TITLE
Relecture A1 - Injection

### ISSUE THREAD

**Issue by romualdszkudlarek** [SPoint42/Top10#6]

**Comment by sprothd** [comment]
Bonjour,

Voici quelques retours pour la relecture de A1 - Injection, dites moi si cela convient.

Supprimer la phrase suivante, qui était présente dans le top 10 2013 et qui n'est plus dans le top 10 2017 :
Considérez que n’importe qui peut envoyer des données non fiables au système, y compris les utilisateurs externes, internes, et administrateurs. (top 10 2013)

Les autres retours :
On les retrouve souvent dans les requêtes SQL, LDAP, XPath, noSQL, commandes OS, parseurs XML, arguments de programme, etc 
-> On les retrouve souvent dans les requêtes SQL, LDAP, XPath, noSQL, commandes systèmes, parseurs XML, entêtes SMTP, expression language (EL), et dans des requêtes de mapping objet-relationnel (ORM).

Les failles d’Injection sont faciles à découvrir lors d’un audit de code, mais plus difficilement via test. Scanners et Fuzzers aident les attaquants à les trouver. (top 10 2013)
-> Les failles de type injection sont faciles à découvrir à partir du code source. Les Scanners et les Fuzzers peuvent aider les attaquants à trouver ce type de faille. 

Considérez la valeur métier de la donnée impactée et la plateforme exécutant l’interpréteur. Toute donnée pourrait être volée, modifiée ou supprimée. Votre réputation pourrait-elle en pâtir? (top 10 2013)
-> Les impacts métier dépendent des besoins de l'application et des données.

des requêtes dynamiques ou des appels non paramétrés sans échappage 
-> des requêtes dynamiques ou des appels non paramétrés sans échappement 

des données hostiles sont utilisées directement ou concaténées, par exemple lors de la construction de requêtes dynamiques, de commandes ou de procédures stockées pour des requêtes SQL ou des commandes OS ;
-> ... ou des commandes systèmes.

La revue de code source est la meilleure manière de détecter si une application est vulnérable à l'Injection, suivie de près par le test automatique de toutes les données d'entrée via les paramètres, en-têtes, URL, cookies, JSON, SOAP et XML. 
-> La revue de code source est la meilleure manière de détecter si les applications sont vulnérables aux Injections, un autre moyen est de mettre en place des tests automatisés approfondies de tous les paramètres fournis en entrées, des en-têtes, des URLs, des cookies, des données JSON, SOAP et XML. 

Note: Attention aux APIs, telles les procédures stockées, qui sont paramétrables, mais qui pourraient introduire une Injection SQL si PL/SQL ou T-SQL concatène requêtes et données ou exécute des données non saines avec EXECUTE IMMEDIATE ou exec().
->  Note: Même lorsque elles sont paramétrées, les procédures stockées peuvent contenir des injections SQL si dans le PL/SQL ou le T-SQL des données sont concaténées dans des requêtes ou que des données malveillantes sont exécutées avec EXECUTE IMMEDIATE ou exec().

Il est conseillé d'utiliser LIMIT et autres contrôles SQL à l'intérieur des requêtes pour empêcher les divulgations massives de données dans le cas d'injection SQL.
-> L'utilisation de l'opérateur LIMIT et d'autres opérateurs SQL dans les requêtes permet d'empêcher les fuites de données massives en cas d'injection SQL.

Scenario #1: -> Scénario #1:
Scenario #2: -> Scénario #2:

**Comment by SPoint42** [comment]
au final, je ne me souviens plus ou on en est de cet element. QQn fait un pull que je review ?
